### ISSUE TITLE
wLaunchELF v4.43a (Build-2017-08-26)

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#12]
@sp193 

This new version has a new bug.  If we try to run some MISC commands -- sometimes it will freeze up the PS2 console.

The previous uLe version [wLaunchELF v4.43a (Build-2017-06-21)] prior to this one did not have this bug.

More details: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=3762

**Comment by sp193** [comment]
By "some", do you only mean MISC/OSDSYS? And neither does it always occur when MISC/OSDSYS is accessed?

**Comment by Jay-Jay-OPL** [comment]
So far the ones that seem to fail are:

after running MISC/PS2Net if you try to run MISC/PS2PowerOff it will fail -- freeze up the console.
after running File Browser, then trying to run MISC/OSDSYS it will fail -- freeze up the console.

I haven't tested the rest.

**Comment by sp193** [comment]
The poweroff issue was fixed in another [build](https://www.sendspace.com/file/2xqep6), along with a PS2SDK update.

I don't really know about the problem behind the OSDSYS option. It does look like it should work....
It may be this [line](https://github.com/ps2dev/ps2sdk/blob/master/ee/kernel/src/initsys.c#L104) that is causing an exception because it is dereferencing _kExecArg in user mode.
But I will have to check with the reference that I used for this, so it will have to wait.

**Comment by Jay-Jay-OPL** [comment]
Thanks.  

Just wanted to confirm that this new version: [wLaunchELF v4.43a (Build-2017-08-27)] fixes the issue with poweroff and that the OSDSYS still fails. 

Was this a silent update?  I didn't see it mentioned anywhere, but I do see that at psx-place and at psx-scene the sendspace URL was updated in your last replies (since the URL matches with the one you supplied above)?  Just hoping for a complete changelog, so I can update the official thread at ps2-home.com

**Comment by sp193** [comment]
I did change the file because I originally planned to reassign that file as the next beta, once it has been confirmed that the FTP issues have been identified to be completely resolved.

Unfortunately, you may have found yet another issue that could be in libkernel, so I now wish to postpone the new beta.

There were no changes were made to LaunchELF itself, only the PS2SDK. Which is why you don't find any new changes here that are related to most of the issues that were resolved.

**Comment by AKuHAK** [comment]
I will try to see if it is possible to modify Travis Cl to automatically generate beta version when ps2sdk is changed.

**Comment by sp193** [comment]
But not all changes will benefit LaunchELF. Do you still want to do that?
For example, at some point, I may decide to delete the legacy libkernel library from the IOP folder. That will not affect LaunchELF at all, but it will still be a commit.

**Comment by AKuHAK** [comment]
I understand that: the key word is 'beta' :) it will not affect github releases page, travis has its own temporary server where public link can live for 2 weeks.
But if you change something in ps2sdk how you can be sure that it will not affect uLe? To my mind the only safe method is to compare hash sum of compiled elf and previous elf. If it is not the same that means that there is some changes that potentially can affect uLaunchELF.

**Comment by sp193** [comment]
Ah okay. I really just wanted to be sure that you do know what to expect. I never worked with Travis before, so I didn't know that it's not considered a Github release.
Thanks!

**Comment by uyjulian** [comment]
Travis CI just compiles and uploads a new version to transfer.sh, so the links live for about 2 weeks.

**Comment by ashwani-talreja** [comment]
Hello, this uLE - 2TB is not working for me :(

I recently bought a SATA Barracuda Internal 2TB hard disk (1.91 TB in system) and bought a SATA to ps2 adapter (didnt convert IDE to SATA as not SATA to PS2 are available). However, the uLE-2TB does not detect that hard disk is connected.

First i thought my adapter is not working but then i connected my 250gb SSD sata drive and loaded uLE-2tb still shows as hard disk not connected. Then i run uLE 4.4.2d or whichever the version is in FMCB 1.93 using older MC, now this one shows my hard disk is connected but not formatted which means the adapter is working fine.

Now i tried my 2 tb hard disk with this older uLE, but it showed as not connected again. So i tricked the system, i connected 250gb ssd first and made it detect the hard disk and then swapped it with my 2TB hard disk and formatted it. It got formatted but based on the 250gb hard disk space which was detected and not 2TB.

Now, i tried to load this hard disk again with uLE-2TB as it was already formatted i was hoping it might show up, but still same issue as hard disk not detected.

Point to note is while loading HDD modules it gives slow beeps and probably HDD drivers/modules are the basic issue here.

Can someone please help and fix this, so that i can use the entire 2TB hard disk with my PS2.

Few things to note are i have the latest FMCB which is 1.953 and OPL 0.9.3 in my MC and Pen Drive. I also tested it against my old MC which has FMCB 1.93 which helped me somehow format it a bit.

Thanks in Advance,
Ash

**Comment by sp193** [comment]
I think the original issue has been resolved as of the September 2017 update. If there is a need to re-open this, please post a comment.

***

@ashwani-talreja: the problem is with your adaptor, if there are initialization problems. Until today, there are no clone/compatible adaptors that are actually 100% compatible because they probably just made them work with specific pieces of software - without actually trying them with official software. So as we change our modules to follow the newer Sony designs, things like them start malfunctioning.

But you're in luck - I just implemented a [series of patches](https://github.com/ps2dev/ps2sdk/issues/49). So perhaps, later revisions of wLaunchELF will become compatible with your adaptor again.

Finally, the "2TB edition" was an unofficial release of wLaunchELF. Please use wLaunchELF, which will contain all necessary fixes. If you still have problems with wLaunchELF (excluding problems with the clone/compatible network adaptor), please open up a new issue ticket here.
